In [9]:
# Initializing an all 0s ndarray
import numpy as np
a = np.zeros((100,1))

# Initializing an all 1s ndarray
b = np.ones((100,1))
c = np.ones((4,10,1)) # count outside in, outermost array has 4 elements, 2nd has 20 element, and the deepest has 1 element

In [11]:
# Create an ndarray full of the same number
d = np.full((1,2), 100)

In [14]:
# Create a ndarray with the same shape as ndarray d populate with the same number 
e = np.full_like(d,5)

array([[5, 5]])

In [17]:
# ndarray of random decimal number
f = np.random.rand(2,2)

In [33]:
# ndarray of random integer values
g = np.random.randint(-1,10, size=(2,2))
# where -1 is min value and 10 is max value

In [37]:
# identity matrix
h = np.identity(5)

In [41]:
arr = np.array([[1,2,3]])
r = np.repeat(arr,3,1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [55]:
# Example of creating ndarray
output = np.ones((5,5))
zeros = np.zeros((3,3))
zeros[1,1] = 9
output[1:-1, 1:-1] = zeros
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be careful when copying array

In [64]:
a = np.array([1,2,3])
b = a # b just pointed to the same piece of memory as a pointed to
b[0] = 10
a

# To prevent the above situations
c = np.array([1,2,3])
d = c.copy()
d[0] = 10
c

array([1, 2, 3])

### Mathematics
#### element wise operation with + , - , * , /

In [74]:
m1 = np.array([[1,2,3]])
m2 = np.array([[1,2,3]])
m1 / m2

array([[1., 1., 1.]])

### Linear Algebra

In [81]:
m1 = np.array([[1,2,3], [1,2,3]])
m2 = np.ones((3,5))

In [82]:
np.matmul(m1,m2)

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

## Ndarray concatenation
##### where axis 0 is vertical and axis 1 is horizontal

In [88]:
features = np.array([
    [2,3],
    [2,3]
])
ones = np.ones((2,1))
np.concatenate((ones, features), axis=1)

array([[2, 2],
       [3, 3]])

### Reorganizing array

In [100]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [111]:
# Vertically stacking vectors
l1 = np.array([0,2,3,4,5])
l2 = np.array([6,7,8,9,10])

np.vstack([l1,l2])
np.hstack([l1,l2])

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Filtering Data in Numpy Array
    

In [118]:
arr1 = np.array([
    [100,1],
    [33,0],
    [55,1]
])
arr2 = arr1[:, -1]

### Reading data using np and split it into features and labels

In [122]:
data = np.loadtxt('./exam_score.csv', delimiter=',', skiprows=1)

In [126]:
# Getting the number of datapoints:
total = data.shape[0]

In [147]:
features = data[0:, 0:-1]
labels = np.expand_dims(data[0:, -1], axis=1)

In [148]:
features

array([[34.62365962, 78.02469282],
       [30.28671077, 43.89499752],
       [35.84740877, 72.90219803],
       [60.18259939, 86.3085521 ],
       [79.03273605, 75.34437644],
       [45.08327748, 56.31637178],
       [61.10666454, 96.51142588],
       [75.02474557, 46.55401354],
       [76.0987867 , 87.42056972],
       [84.43281996, 43.53339331],
       [95.86155507, 38.22527806],
       [75.01365839, 30.60326323],
       [82.30705337, 76.4819633 ],
       [69.36458876, 97.71869196],
       [39.53833914, 76.03681085],
       [53.97105215, 89.20735014],
       [69.07014406, 52.74046973],
       [67.94685548, 46.67857411],
       [70.66150955, 92.92713789],
       [76.97878373, 47.57596365],
       [67.37202755, 42.83843832],
       [89.67677575, 65.79936593],
       [50.53478829, 48.85581153],
       [34.21206098, 44.2095286 ],
       [77.92409145, 68.97235999],
       [62.27101367, 69.95445795],
       [80.19018075, 44.82162893],
       [93.1143888 , 38.80067034],
       [61.83020602,

In [149]:
labels

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [ ]:
## Append
# Whether the axis is 0 or 1, the original ndarray is always there , i mean like how we put it is always VERTICAL
# it is always VERTICAL like [
#   [1,2]
#   [2,4]
#]